name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on:  windows,ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 20.9.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.20.9.0 }}
    - run: npm install
    - run: npm test
